monit/config/routes.rb
Rails.application.routes.draw do
  resources :hosts

root 'hosts#index'

end

monit/app/models/host.rb
class Host < ActiveRecord::Base
end

monit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

monit/app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: [:show, :edit, :update, :destroy]

  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
  end

  # GET /hosts/new
  def new
    @host = Host.new
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(host_params)

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: 'Host was successfully created.' }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1
  # PATCH/PUT /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to @host, notice: 'Host was successfully updated.' }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url, notice: 'Host was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_params
      params.require(:host).permit(:name)
    end
end

monit/app/helpers/application_helper.rb
module ApplicationHelper
end

monit/app/helpers/hosts_helper.rb
module HostsHelper
end

monit/app/views/hosts/_form.html.erb
<%= form_for(@host) do |f| %>
  <% if @host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
      <% @host.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

monit/app/views/hosts/edit.html.erb
<h1>Editing Host</h1>

<%= render 'form' %>

<%= link_to 'Show', @host %> |
<%= link_to 'Back', hosts_path %>

monit/app/views/hosts/index.html.erb
<p id="notice"><%= notice %></p>


Host add (input IP and click Enter)
<input id='host_add' />
<br/>

Host remove (input IP and click Enter)
<input id='host_remove' />
<br/>

<div id='hosts'>
</div>

monit/app/views/hosts/new.html.erb
<h1>New Host</h1>

<%= render 'form' %>

<%= link_to 'Back', hosts_path %>

monit/app/views/hosts/show.html.erb
<p id="notice"><%= notice %></p>

<input id='hosts-interval' />
<div id='hosts'>
</div>

<p>
  <strong>Name:</strong>
  <%= @host.name %>
</p>

<%= link_to 'Edit', edit_host_path(@host) %> |
<%= link_to 'Back', hosts_path %>

monit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Monit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>